#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROJECTS = ROOT / "projects"
EXP_DIR_RE = re.compile(r"^\d{4}-\d{2}-\d{2}_[a-z0-9][a-z0-9-]*$")
EXP_STATES = {"planned", "ready", "running", "blocked", "completed", "superseded"}
CHECK_STATES = {"pending", "running", "pass", "fail", "blocked", "not_applicable"}
ICONS = {"pending": "[ ]", "running": "[~]", "pass": "[x]", "fail": "[!]", "blocked": "[-]", "not_applicable": "[n/a]"}


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ValueError(f"missing required file: {path.relative_to(ROOT)}")
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON in {path.relative_to(ROOT)}: {exc}")


def project_dirs():
    if not PROJECTS.exists():
        return []
    return sorted(p for p in PROJECTS.iterdir() if p.is_dir())


def experiment_dirs():
    out = []
    for project_dir in project_dirs():
        exp_root = project_dir / "experiments"
        if exp_root.exists():
            out.extend(sorted(p for p in exp_root.iterdir() if p.is_dir()))
    return out


def rel(path: Path):
    return path.relative_to(ROOT).as_posix()


def render_checklist(checks):
    lines = [
        "# Checklist",
        "",
        "> Generated from `checks.json`. Do not edit directly.",
        "",
    ]
    for check in checks.get("checks", []):
        status = check["status"]
        lines.append(f"- {ICONS[status]} **{check['id']}** — {check['description']} (`{status}`)")
        for evidence in check.get("evidence", []):
            if isinstance(evidence, str):
                lines.append(f"  - evidence: {evidence}")
            else:
                lines.append(f"  - {evidence.get('label', 'evidence')}: {evidence.get('ref', evidence.get('path', ''))}")
    lines.append("")
    return "\n".join(lines)


def render_handoff(experiment, state):
    checkpoint = state.get("last_checkpoint")
    checkpoint_text = "None yet."
    if checkpoint:
        checkpoint_text = f"`{checkpoint['path']}` — {checkpoint.get('summary', '')}"
    blockers = state.get("blockers", []) or ["None."]
    findings = state.get("important_findings", []) or ["None yet."]
    lines = [
        "# Current Handoff",
        "",
        "> Generated from `experiment.json` + `state.json`. Do not edit directly.",
        "",
        f"**Experiment:** `{experiment['id']}`  ",
        f"**Status:** `{state['status']}`",
        "",
        "## Question",
        "",
        experiment["question"].strip(),
        "",
        "## Current focus",
        "",
        state.get("current_focus", "None recorded."),
        "",
        "## Last durable checkpoint",
        "",
        checkpoint_text,
        "",
        "## Exact next action",
        "",
        state.get("next_action", "No next action recorded."),
        "",
        "## Blockers",
        "",
    ]
    lines.extend(f"- {item}" for item in blockers)
    lines.extend(["", "## Important findings", ""])
    lines.extend(f"- {item}" for item in findings)
    lines.extend([
        "",
        "## Resume protocol",
        "",
        "1. Read this file and the experiment-local `AGENTS.md`.",
        "2. Read the last checkpoint above.",
        "3. Verify live upstream refs before mutation.",
        "4. Continue from the exact next action; do not redo passed work without evidence.",
        "5. Before handoff, append a checkpoint, update machine state/checks, run `python tools/lab.py sync`, then `python tools/lab.py validate`.",
        "",
    ])
    return "\n".join(lines)


def build_catalog():
    items = []
    for exp_dir in experiment_dirs():
        experiment = load_json(exp_dir / "experiment.json")
        state = load_json(exp_dir / "state.json")
        items.append({
            "id": experiment["id"],
            "project": experiment["project"],
            "path": rel(exp_dir),
            "status": state["status"],
            "question": experiment["question"],
            "updated_at": state["updated_at"],
        })
    items.sort(key=lambda item: (item["project"], item["id"]))
    return {"schema_version": "lab.catalog.v1", "experiments": items}


def render_catalog(catalog):
    lines = [
        "# Experiment Catalog",
        "",
        "> Generated by `python tools/lab.py sync`. Do not edit directly.",
        "",
        "| Project | Experiment | Status | Question |",
        "|---|---|---|---|",
    ]
    for item in catalog["experiments"]:
        question = item["question"].replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{item['project']}` | [`{item['id']}`]({item['path']}/README.md) | `{item['status']}` | {question} |")
    lines.append("")
    return "\n".join(lines)


def sync():
    for exp_dir in experiment_dirs():
        experiment = load_json(exp_dir / "experiment.json")
        state = load_json(exp_dir / "state.json")
        checks = load_json(exp_dir / "checks.json")
        (exp_dir / "CHECKLIST.md").write_text(render_checklist(checks), encoding="utf-8")
        (exp_dir / "HANDOFF.md").write_text(render_handoff(experiment, state), encoding="utf-8")
    catalog = build_catalog()
    (ROOT / "catalog.json").write_text(json.dumps(catalog, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (ROOT / "CATALOG.md").write_text(render_catalog(catalog), encoding="utf-8")


def validate():
    errors = []
    for name in ("README.md", "AGENTS.md", "LAB_SPEC.md", "CATALOG.md", "catalog.json"):
        if not (ROOT / name).exists():
            errors.append(f"missing root file: {name}")

    seen_ids = set()
    for project_dir in project_dirs():
        try:
            project = load_json(project_dir / "project.json")
        except ValueError as exc:
            errors.append(str(exc))
            continue
        project_id = project.get("id")
        if project_id != project_dir.name:
            errors.append(f"{rel(project_dir / 'project.json')}: id must equal directory name")
        exp_root = project_dir / "experiments"
        if not exp_root.exists():
            continue

        for exp_dir in sorted(p for p in exp_root.iterdir() if p.is_dir()):
            if not EXP_DIR_RE.fullmatch(exp_dir.name):
                errors.append(f"invalid experiment directory name: {rel(exp_dir)}")
            try:
                experiment = load_json(exp_dir / "experiment.json")
                state = load_json(exp_dir / "state.json")
                checks = load_json(exp_dir / "checks.json")
            except ValueError as exc:
                errors.append(str(exc))
                continue

            exp_id = experiment.get("id")
            if not exp_id:
                errors.append(f"{rel(exp_dir)}: experiment id missing")
                continue
            if exp_id in seen_ids:
                errors.append(f"duplicate experiment id: {exp_id}")
            seen_ids.add(exp_id)

            if experiment.get("schema_version") != "lab.experiment.v1":
                errors.append(f"{exp_id}: unsupported experiment schema")
            if experiment.get("project") != project_id:
                errors.append(f"{exp_id}: project mismatch")
            if state.get("schema_version") != "lab.state.v1" or state.get("experiment_id") != exp_id:
                errors.append(f"{exp_id}: invalid state identity/schema")
            if state.get("status") not in EXP_STATES:
                errors.append(f"{exp_id}: invalid state status")
            if checks.get("schema_version") != "lab.checks.v1" or checks.get("experiment_id") != exp_id:
                errors.append(f"{exp_id}: invalid checks identity/schema")

            ids = set()
            for check in checks.get("checks", []):
                cid = check.get("id")
                if not cid or cid in ids:
                    errors.append(f"{exp_id}: duplicate/missing check id {cid!r}")
                ids.add(cid)
                if check.get("status") not in CHECK_STATES:
                    errors.append(f"{exp_id}/{cid}: invalid status")
                if check.get("status") == "pass" and not check.get("evidence"):
                    errors.append(f"{exp_id}/{cid}: PASS requires evidence")
                for evidence in check.get("evidence", []):
                    if isinstance(evidence, dict) and evidence.get("path"):
                        if not (exp_dir / evidence["path"]).exists():
                            errors.append(f"{exp_id}/{cid}: missing evidence path {evidence['path']}")

            checkpoint = state.get("last_checkpoint")
            if checkpoint:
                cp_path = checkpoint.get("path")
                if not cp_path or not (exp_dir / cp_path).exists():
                    errors.append(f"{exp_id}: missing last checkpoint {cp_path!r}")

            for upstream in experiment.get("upstream", []):
                if upstream.get("kind") == "git":
                    revision = upstream.get("revision", "")
                    if not re.fullmatch(r"[0-9a-f]{40}", revision):
                        errors.append(f"{exp_id}: git revision must be exact 40-char SHA")

            if state.get("status") == "completed":
                if not (exp_dir / "conclusion.md").exists():
                    errors.append(f"{exp_id}: completed experiment missing conclusion.md")
                run_root = exp_dir / "runs"
                if not run_root.exists() or not any(p.is_dir() for p in run_root.iterdir()):
                    errors.append(f"{exp_id}: completed experiment requires at least one run")

            checklist_path = exp_dir / "CHECKLIST.md"
            if not checklist_path.exists() or checklist_path.read_text(encoding="utf-8") != render_checklist(checks):
                errors.append(f"{exp_id}: CHECKLIST.md stale; run sync")
            handoff_path = exp_dir / "HANDOFF.md"
            if not handoff_path.exists() or handoff_path.read_text(encoding="utf-8") != render_handoff(experiment, state):
                errors.append(f"{exp_id}: HANDOFF.md stale; run sync")

    try:
        catalog = build_catalog()
        expected_json = json.dumps(catalog, indent=2, sort_keys=True) + "\n"
        if (ROOT / "catalog.json").read_text(encoding="utf-8") != expected_json:
            errors.append("catalog.json stale; run sync")
        if (ROOT / "CATALOG.md").read_text(encoding="utf-8") != render_catalog(catalog):
            errors.append("CATALOG.md stale; run sync")
    except Exception as exc:
        errors.append(f"catalog validation failed: {exc}")

    return errors


def main():
    parser = argparse.ArgumentParser(description="Durable experiment-lab maintenance tool")
    parser.add_argument("command", choices=("sync", "validate"))
    args = parser.parse_args()
    if args.command == "sync":
        sync()
    errors = validate()
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("lab validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
